apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vanguard-sso-db
  namespace: vanguard-sso-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: sso
      owner: sso
      secret:
        name: vanguard-sso-db-secrets
  storage:
    size: 256Mi
    storageClass: longhorn
