apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vanguard-sso-db-secrets
  namespace: vanguard-sso-db
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vanguard-sso-db-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: vanguard/production/pg/sso
        property: username
    - secretKey: password
      remoteRef:
        key: vanguard/production/pg/sso
        property: db_password
