apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflare-ddns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/cloudflare-ddns/overlays/use1
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflare-ddns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
