apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-vanguard-permissions
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/cloudnative-postgres/overlays/vanguard-permissions
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: vanguard-permissions-db
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
