apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis-sentry
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/redis-operator/overlays/sentry
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: sentry-redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
