apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustlens-backend
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: backend=ghcr.io/vanguard-enterprise/rustlens-backend:main
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/backend.pull-secret: pullsecret:argocd/ghcr-image-updater
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-git
    argocd-image-updater.argoproj.io/write-back-target: kustomization:applications/rustlens/overlays/backend
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/rustlens/overlays/backend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: rustlens-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
