apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rustlens-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/rustlens/overlays/backend
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: rustlens-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
