apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vanguard-ingress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Vanguard-Enterprise/v-deployments
    path: applications/vanguard-services/overlays/ingress
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: vanguard-frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
