apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vngenterprise
  namespace: traefik
spec:
  secretName: vngenterprise-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.mancini.beer"
  dnsNames:
    - "*.mancini.beer"
    - mancini.beer