apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rustlens
  namespace: rustlens-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: rustlens
      owner: rustlens
      secret:
        name: rustlens-pg-bootstrap
  storage:
    size: 10Gi
    storageClass: longhorn
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
