apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: rustlens
  namespace: rustlens-db
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: rustlens
      owner: rustlens
      secret:
        name: rustlens-pg-bootstrap
  storage:
    size: 20Gi
    storageClass: longhorn
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-rustlens-use1
      endpointURL: https://s3.us-east-1.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: cnpg-rustlens-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-rustlens-backup
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"
