apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustlens-pg-bootstrap
  namespace: rustlens-db
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rustlens-pg-bootstrap
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: "{{ .username }}"
        password: "{{ .db_password }}"
  data:
    - secretKey: username
      remoteRef:
        key: rustlens/production/pg/rustlens
        property: username
    - secretKey: db_password
      remoteRef:
        key: rustlens/production/pg/rustlens
        property: db_password
