apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-rustlens-backup
  namespace: rustlens-db
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cnpg-rustlens-backup
    creationPolicy: Owner
  data:
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: cnpg/rustlens/backup
        property: AWS_ACCESS_KEY_ID
    - secretKey: ACCESS_SECRET_KEY
      remoteRef:
        key: cnpg/rustlens/backup
        property: AWS_SECRET_ACCESS_KEY
