apiVersion: v1
kind: Service
metadata:
  name: rustlens-pooled-rw-lb
  namespace: rustlens-db
  annotations:
    metallb.universe.tf/loadBalancerIPs: 10.1.50.151
    metallb.universe.tf/address-pool: use1-pool
spec:
  type: LoadBalancer
  selector:
    cnpg.io/poolerName: rustlens-pooled-rw
  ports:
    - name: pgbouncer
      port: 5432
      protocol: TCP
      targetPort: pgbouncer
