apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  revisionHistoryLimit: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0
  template:
    spec:
      securityContext: {}
      volumes:
        - name: config
          configMap:
            defaultMode: 420
            name: nats-config
  volumeClaimTemplates:
    - metadata:
        name: nats-js
      spec:
        volumeMode: Filesystem
