apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: netbird-client
  namespace: netbird-client
spec:
  serviceName: netbird-client
  replicas: 3
  selector:
    matchLabels:
      app: netbird-client
  template:
    metadata:
      labels:
        app: netbird-client
    spec:
      containers:
        - name: client
          image: netbirdio/netbird:0.70.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: netbird-client-setup
          env:
            - name: NB_MANAGEMENT_URL
              value: https://netbird.vngenterprise.com
          volumeMounts:
            - name: client-data
              mountPath: /var/lib/netbird
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
        - name: s3-forward
          image: alpine/socat:1.7.4.4
          imagePullPolicy: IfNotPresent
          args:
            - "-d"
            - "TCP-LISTEN:443,fork,reuseaddr"
            - "TCP:backup-storage.vngenterprise.com:443"
          ports:
            - name: s3
              containerPort: 443
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsNonRoot: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
  volumeClaimTemplates:
    - metadata:
        name: client-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
