---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: loki
  labels:
    app: loki
spec:
  type: ClusterIP
  selector:
    app: loki
  ports:
    - name: http
      port: 3100
      targetPort: http
    - name: grpc
      port: 9095
      targetPort: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: loki-headless
  namespace: loki
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: loki
  ports:
    - name: gossip
      port: 7946
      targetPort: gossip
