apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: sentry-db
  namespace: sentry
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 1Gi }
  bootstrap:
    initdb:
      database: sentry
      owner: sentry
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-sentry-use1
      endpointURL: https://backup-storage.vngenterprise.com
      s3Credentials:
        accessKeyId:
          name: cnpg-sentry-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-sentry-backup
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"
