apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-root
  namespace: rustfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rustfs-root
    creationPolicy: Owner
  data:
    - secretKey: ROOT_USER
      remoteRef:
        key: rustfs/cluster
        property: ROOT_USER
    - secretKey: ROOT_PASSWORD
      remoteRef:
        key: rustfs/cluster
        property: ROOT_PASSWORD
