apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: hyplex-rustfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - name: rustfs
          image: rustfs/rustfs:latest
          args:
            - --console-enable
            - /data
          ports:
            - name: s3
              containerPort: 9000
              protocol: TCP
            - name: console
              containerPort: 9001
              protocol: TCP
          envFrom:
            - secretRef:
                name: rustfs-root-secrets
          volumeMounts:
            - name: data
              mountPath: /data
            - name: data
              mountPath: /logs
              subPath: logs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rustfs-data
