apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustfs-root-secrets
  namespace: hyplex-rustfs
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rustfs-root-secrets
    creationPolicy: Owner
  data:
    - secretKey: RUSTFS_ACCESS_KEY
      remoteRef:
        key: "rustfs/root"
        property: RUSTFS_ACCESS_KEY
    - secretKey: RUSTFS_SECRET_KEY
      remoteRef:
        key: "rustfs/root"
        property: RUSTFS_SECRET_KEY
