apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: longhorn-backup-storage
  namespace: longhorn-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: longhorn-backup-storage
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: "longhorn/backup-storage"
        property: "AWS_ACCESS_KEY_ID"
    - secretKey: AWS_ENDPOINTS
      remoteRef:
        key: "longhorn/backup-storage"
        property: "AWS_ENDPOINTS"
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: "longhorn/backup-storage"
        property: "AWS_SECRET_ACCESS_KEY"
