apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alloy-receiver
  namespace: alloy-receiver
  labels:
    instance: primary
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: alloy
      app.kubernetes.io/instance: alloy-receiver
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 60s
