apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-monthly
  namespace: longhorn-system
spec:
  cron: "0 0 1 * *"
  task: backup
  retain: 12
  concurrency: 2
  groups:
    - default
