apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tempo-global-env
  namespace: tempo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: tempo-global-env
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: monitoring/tempo
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: monitoring/tempo
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: BUCKET_NAME
      remoteRef:
        key: monitoring/tempo
        property: BUCKET_NAME
