apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tempo
  namespace: tempo
  labels:
    instance: primary
spec:
  selector:
    matchLabels:
      app: tempo
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
      relabelings:
        - targetLabel: job
          replacement: tempo/tempo
