apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentry-clickhouse-secret
  namespace: sentry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sentry-clickhouse-secret
    creationPolicy: Owner
  data:
    - secretKey: default-password
      remoteRef: { key: sentry/clickhouse, property: DEFAULT_PASSWORD }
    - secretKey: sentry-password
      remoteRef: { key: sentry/clickhouse, property: SENTRY_PASSWORD }
