apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentry-web
  namespace: sentry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sentry-web
    creationPolicy: Owner
  data:
    - secretKey: SENTRY_SECRET_KEY
      remoteRef: { key: sentry/web, property: SECRET_KEY }
    - secretKey: SENTRY_OPTIONS_SYSTEM_ADMIN_EMAIL
      remoteRef: { key: sentry/web, property: SENTRY_OPTIONS_SYSTEM_ADMIN_EMAIL }
    - secretKey: SENTRY_OPTIONS_SYSTEM_ADMIN_PASSWORD
      remoteRef: { key: sentry/web, property: SENTRY_OPTIONS_SYSTEM_ADMIN_PASSWORD }
