apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sentry-saml
  namespace: sentry
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sentry-saml
    creationPolicy: Owner
  data:
    - secretKey: IDP_SSO_URL
      remoteRef: { key: sentry/saml, property: IDP_SSO_URL }
    - secretKey: IDP_ENTITY_ID
      remoteRef: { key: sentry/saml, property: IDP_ENTITY_ID }
    - secretKey: IDP_X509_CERT
      remoteRef: { key: sentry/saml, property: IDP_X509_CERT }
