apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - external-secret-web.yaml
  - external-secret-saml.yaml
  - external-secret-filestore.yaml
  - external-secret-clickhouse.yaml
  - external-secret-redis.yaml
  - podmonitors.yaml
  - sentry.vngenterprise.com.yaml
