apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: identity-service-secrets
  namespace: vanguard-identity
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: identity-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_PRIVATE_KEY: "{{ .jwt_private_key }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        DATABASE_URL: "postgres://{{ .pg_username }}:{{ .pg_password }}@vanguard-identity-db-rw.vanguard-identity-db.svc.cluster.local:5432/identity?sslmode=require"
  data:
    - secretKey: jwt_private_key
      remoteRef:
        key: vanguard/production/identity
        property: JWT_PRIVATE_KEY
    - secretKey: encryption_key
      remoteRef:
        key: vanguard/production/identity
        property: ENCRYPTION_KEY
    - secretKey: pg_username
      remoteRef:
        key: vanguard/production/pg/identity
        property: username
    - secretKey: pg_password
      remoteRef:
        key: vanguard/production/pg/identity
        property: db_password
