apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: vanguard-identity-db
  namespace: vanguard-identity-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: identity
      owner: identity
      secret:
        name: vanguard-identity-db-secrets
  storage:
    size: 256Mi
    storageClass: longhorn
