apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: permissions-service-secrets
  namespace: vanguard-permissions
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: permissions-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_PUBLIC_KEY: "{{ .jwt_public_key }}"
        DATABASE_URL: "postgres://{{ .pg_username }}:{{ .pg_password }}@vanguard-permissions-db-rw.vanguard-permissions-db.svc.cluster.local:5432/permissions?sslmode=require"
  data:
    - secretKey: jwt_public_key
      remoteRef:
        key: vanguard/production/jwt
        property: JWT_PUBLIC_KEY
    - secretKey: pg_username
      remoteRef:
        key: vanguard/production/pg/permissions
        property: username
    - secretKey: pg_password
      remoteRef:
        key: vanguard/production/pg/permissions
        property: db_password
