apiVersion: v1
kind: Service
metadata:
  name: permissions-service
  namespace: vanguard-permissions
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: grpc
      port: 9091
      targetPort: 9091
      protocol: TCP
  selector:
    app: permissions-service
