apiVersion: v1
kind: ConfigMap
metadata:
  name: rustlens-backend-config
  namespace: rustlens-backend
data:
  PORT: "8080"
  BOT_TARGET_SHARDS: "2"
  BOT_HEARTBEAT_TTL_SECONDS: "45"
  BATTLEMETRICS_SERVER_POLL_INTERVAL_SECONDS: "10"
  APP_ORIGIN: "https://rustlens.com"
  ALLOW_AUTH_DEBUG_TOKENS: "false"
