apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: rustlens-backend-secrets
  namespace: rustlens-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: rustlens-backend-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        APP_API_INTERNAL_SECRET: "{{ .APP_API_INTERNAL_SECRET }}"
        APP_SESSION_SECRET: "{{ .APP_SESSION_SECRET }}"
        BOT_SERVICE_JWT_SECRET: "{{ .BOT_SERVICE_JWT_SECRET }}"
        STEAM_API_KEY: "{{ .STEAM_API_KEY }}"
        BATTLEMETRICS_API_KEY: "{{ .BATTLEMETRICS_API_KEY }}"
        DISCORD_CLIENT_SECRET: "{{ .DISCORD_CLIENT_SECRET }}"
        POSTGRES_URL: "postgres://{{ .pg_username }}:{{ .pg_password }}@rustlens-pooled-rw.rustlens-db.svc.cluster.local:5432/rustlens?sslmode=require"
        REDIS_URL: "redis://:{{ .redis_password }}@rustlens-redis-master.rustlens-redis.svc.cluster.local:6379/0"
  data:
    - secretKey: APP_API_INTERNAL_SECRET
      remoteRef:
        key: rustlens/production/shared
        property: APP_API_INTERNAL_SECRET
    - secretKey: APP_SESSION_SECRET
      remoteRef:
        key: rustlens/production/shared
        property: APP_SESSION_SECRET
    - secretKey: BOT_SERVICE_JWT_SECRET
      remoteRef:
        key: rustlens/production/shared
        property: BOT_SERVICE_JWT_SECRET
    - secretKey: STEAM_API_KEY
      remoteRef:
        key: rustlens/production/backend
        property: STEAM_API_KEY
    - secretKey: BATTLEMETRICS_API_KEY
      remoteRef:
        key: rustlens/production/backend
        property: BATTLEMETRICS_API_KEY
    - secretKey: DISCORD_CLIENT_SECRET
      remoteRef:
        key: rustlens/production/backend
        property: DISCORD_CLIENT_SECRET
    - secretKey: pg_username
      remoteRef:
        key: rustlens/production/pg/rustlens
        property: username
    - secretKey: pg_password
      remoteRef:
        key: rustlens/production/pg/rustlens
        property: db_password
    - secretKey: redis_password
      remoteRef:
        key: rustlens/production/redis
        property: password
