apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-pull-secret
  namespace: rustlens-backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-pull-secret
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .mysecret | toString }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: dockerconfig
