apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
- prometheusrule.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-backend
  digest: sha256:faa24fd31179dfc0a031ce03c25df6ed886d6c02b343e58c209c4443dfccc1a2
