apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-backend
  digest: sha256:77f3c81d14c58969a729590b731aa634a45da789a0205ba39890b0132d5526f0
