apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
- prometheusrule.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-backend
  digest: sha256:8dc71b2d871ac53e2f8fdbb265f90a9ed2fd95631699ebf3010da75b41e2301a
