apiVersion: v1
kind: Service
metadata:
  name: rustlens-backend
  namespace: rustlens-backend
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  selector:
    app: rustlens-backend
