apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sso-service-secrets
  namespace: vanguard-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sso-service-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        JWT_PUBLIC_KEY: "{{ .jwt_public_key }}"
        ENCRYPTION_KEY: "{{ .encryption_key }}"
        DATABASE_URL: "postgres://{{ .pg_username }}:{{ .pg_password }}@vanguard-sso-db-rw.vanguard-sso-db.svc.cluster.local:5432/sso?sslmode=require"
  data:
    - secretKey: jwt_public_key
      remoteRef:
        key: vanguard/production/jwt
        property: JWT_PUBLIC_KEY
    - secretKey: encryption_key
      remoteRef:
        key: vanguard/production/sso
        property: ENCRYPTION_KEY
    - secretKey: pg_username
      remoteRef:
        key: vanguard/production/pg/sso
        property: username
    - secretKey: pg_password
      remoteRef:
        key: vanguard/production/pg/sso
        property: db_password
