apiVersion: v1
kind: ConfigMap
metadata:
  name: vngenterprise-com-config
  namespace: vngenterprise-com
data:
  PORT: "3000"
  NODE_ENV: "production"
  AUTH_URL: "https://vngenterprise.com"
  NEXT_TELEMETRY_DISABLED: "1"
