apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vngenterprise-com-secrets
  namespace: vngenterprise-com
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: vngenterprise-com-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: vngenterprise-com/production
        property: AUTH_SECRET
