apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: auth-service
  namespace: auth-service-db
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised
  bootstrap:
    initdb:
      database: auth
      owner: auth
      secret:
        name: auth-service-db-secrets
  storage:
    size: 2Gi
    storageClass: longhorn
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
  backup:
    barmanObjectStore:
      destinationPath: s3://postgres/auth-service/
      endpointURL: https://557bf24a406c7d5b80d2874f6937616c.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: auth-service-db-secrets
          key: S3_ACCESS_KEY_ID
        secretAccessKey:
          name: auth-service-db-secrets
          key: S3_SECRET_ACCESS_KEY
      wal:
        compression: gzip
