apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: r2-credentials
  namespace: hyplex-game
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: r2-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: endpoint
      remoteRef:
        key: "hyplex/production/game-servers"
        property: R2_ENDPOINT
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: access-key-id
      remoteRef:
        key: "hyplex/production/game-servers"
        property: R2_ACCESS_KEY_ID
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: secret-access-key
      remoteRef:
        key: "hyplex/production/game-servers"
        property: R2_SECRET_ACCESS_KEY
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
