apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pyroscope
  namespace: pyroscope
  labels:
    instance: primary
spec:
  selector:
    matchLabels:
      app: pyroscope
  endpoints:
    - port: http
      path: /metrics
      interval: 60s
