apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
- prometheusrule.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-frontend
  digest: sha256:0c14219dbb5c95f87bea671a4618d1291b9669b1567f6716984400829b997b66
