apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-frontend
  digest: sha256:e8d4eb2e4542aa7b92ac4363857321f836e90e1a1d1c1d27f72aefd2534ce175
