apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- service.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-frontend
  digest: sha256:c7043642d90b27a94f64c76de51c0554c5d263908cd94bdbed84536ca04d3459
