apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: hyplex-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
    - secretKey: JWT_PRIVATE_KEY
      remoteRef:
        key: hyplex/production/auth
        property: JWT_PRIVATE_KEY
    - secretKey: DB_PASSWORD
      remoteRef:
        key: hyplex/production/pg/auth
        property: db_password
