apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-bot
  digest: sha256:810d6ef05b78f3c133d7fdef38d5abe8d25fdbb31a14857357880f5ced90d6db
