apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
- prometheusrule.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-bot
  digest: sha256:cc501b99d8d89c684822704f3272a87aec8f156d8f8a1ab87c56d8a55a5eccd6
