apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- configmap.yaml
- github-pull-secret.yaml
- external-secret.yaml
- deployment.yaml
images:
- name: ghcr.io/vanguard-enterprise/rustlens-bot
  digest: sha256:b5282b510b8c80ad233ba0e8d9365f579ead255d8bb4a6a60687dd3e16951423
