apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-rules-argocd
  namespace: grafana
  labels:
    grafana_alert: "1"
data:
  rules-argocd.yaml: |
    apiVersion: 1
    groups:
      - orgId: 1
        name: argocd
        folder: platform
        interval: 1m
        rules:
          - uid: argocd-app-out-of-sync
            title: ArgoCDAppOutOfSync
            condition: A
            isPaused: true
            data:
              - refId: A
                relativeTimeRange: { from: 1800, to: 0 }
                datasourceUid: mimir
                model:
                  expr: 'argocd_app_info{sync_status!="Synced"}'
                  refId: A
            noDataState: OK
            for: 30m
            labels:
              severity: warning
              team: platform
            annotations:
              summary: "ArgoCD app {{ $labels.name }} out of sync >30m"

          - uid: argocd-app-degraded
            title: ArgoCDAppDegraded
            condition: A
            isPaused: true
            data:
              - refId: A
                relativeTimeRange: { from: 600, to: 0 }
                datasourceUid: mimir
                model:
                  expr: 'argocd_app_info{health_status="Degraded"}'
                  refId: A
            noDataState: OK
            for: 10m
            labels:
              severity: critical
              team: platform
            annotations:
              summary: "ArgoCD app {{ $labels.name }} Degraded"
