apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-db
  namespace: grafana
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: longhorn
  resources:
    requests: { cpu: 100m, memory: 256Mi }
    limits:   { cpu: 500m, memory: 1Gi }
  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-grafana-use1
      endpointURL: https://s3.us-east-1.wasabisys.com
      s3Credentials:
        accessKeyId:
          name: cnpg-grafana-backup
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-grafana-backup
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "14d"
