apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-db-twice-daily
  namespace: grafana
spec:
  schedule: "0 0 3,15 * * *"
  backupOwnerReference: self
  cluster:
    name: grafana-db
  method: barmanObjectStore
