apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-image-updater-git
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-image-updater-git
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: argocd-image-updater/git
        property: username
    - secretKey: password
      remoteRef:
        key: argocd-image-updater/git
        property: password
